### ISSUE TITLE
Tag Templates

### ISSUE THREAD

**Issue by Jessie-Park** [vojes-enterprises/vojes-enterprises.github.io#4]
[http://smm.zoomquiet.top/data/20110511083224/index.html](url)

This will be updated to list the elements we currently need to make templates for as we move forward.

**Comment by Jessie-Park** [comment]
![2019-08-28-155649_269x48_scrot](https://user-images.githubusercontent.com/53576700/63872019-80902900-c9ac-11e9-897d-70522764b2d8.png)
Search Bar
Background color of button: #25384A
Color of magnifying glass: beige (until we decide on a white)


HTML
```HTML
<form action="" method="get">
    <div>
        <input type="text" name="search" placeholder="Search">
    
        <button class="btn"><i class="fa fa-search"></i></button>
    </div>
</form>
```

CSS
```CSS
.btn {
  background-color: #25384A; /* Blue background */
  border: none; /* Remove borders */
  color: beige; /* White text */
  padding: 6px 10px; /* Some padding */
  font-size: 16px; /* Set a font size */
  cursor: pointer; /* Mouse pointer on hover */
}
```

**Comment by Jessie-Park** [comment]
![2019-08-28-193819_483x325_scrot](https://user-images.githubusercontent.com/53576700/63887131-a4169c00-c9cb-11e9-8f27-b6a23a5787ce.png)
Log in

HTML
```HTML
<form>
    <div class="login">
        <h2 class="greet">Welcome to <br> Vojes Enterprise</h2>
        <div class="input">
            <i class="fa fa-user"></i>
            <input class="input-field" type="text" placeholder="Username">
        </div>
        <div class="input">
            <i class="fa fa-lock"></i>
            <input class="input-field" type="text" placeholder="Password">
        </div>
        <div class="button">
            <button class="submit">Log In</button>
        </div>
    </div>
</form>
```

CSS
```CSS
.login {
    position: relative;
    background-color: #25384A;
    width: 35%;
}

.greet {
    text-align: center;
    font-family: 'Lexend Deca', sans-serif;
    padding-top: 25px;
    color: beige;
}

.input {
    position: relative;
    margin-left: 17.5%;
    margin-right: 17.5%;
    text-align: center
}

.input-field {
    width: 94.5%;
    line-height: 3;
    text-indent: 30px;
    margin-bottom: 10px;
    border-radius: 50px;
    font-family: 'Lexend Deca', sans-serif;
}

.fa {
    position: absolute;
    padding: 16px;
}

.button {
    position: relative;
    text-align: center;
    height: 75px;
    margin-top: 10px;
}

.submit {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    width: 50%;
    height: 50%;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    font-family: 'Lexend Deca', sans-serif;
}
```
